import React, { useState } from 'react';
import { usePortfolio } from '../../../context/PortfolioContext';
import { Category, ContactSettings, LocalizedString, NavItem, SEOSettings, StatItem } from '../../../types/portfolio';
import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from 'lucide-react';

type SiteMode = 'categories' | 'stats' | 'navigation' | 'seo' | 'contact';
const local = (en: string, ar = ''): LocalizedString => ({ en, ar });
const inputClass = 'w-full rounded-xl border border-white/10 bg-black/50 px-3 py-2 text-xs text-white';

export const AdminSiteContentTab: React.FC = () => {
  const { data, saveData, addToast } = usePortfolio();
  const [mode, setMode] = useState<SiteMode>('categories');
  const [saving, setSaving] = useState(false);
  const [categories, setCategories] = useState<Category[]>([...(data.categories || [])].sort((a, b) => a.order - b.order));
  const [stats, setStats] = useState<StatItem[]>([...(data.stats || [])].sort((a, b) => a.order - b.order));
  const [navItems, setNavItems] = useState<NavItem[]>([...(data.navItems || [])].sort((a, b) => a.order - b.order));
  const [seo, setSeo] = useState<SEOSettings>({ ...data.seo });
  const [contact, setContact] = useState<ContactSettings>({ ...data.contact, formFields: { ...data.contact.formFields } });

  const save = async () => {
    if (saving) return;
    setSaving(true);
    try {
      const ok = await saveData({ ...data, categories, stats, navItems, seo, contact });
      addToast(ok ? 'Site content saved.' : 'Site content could not be saved.', ok ? 'success' : 'error');
    } finally { setSaving(false); }
  };

  const move = <T extends { order: number }>(list: T[], setList: React.Dispatch<React.SetStateAction<T[]>>, index: number, direction: -1 | 1) => {
    const target = index + direction;
    if (target < 0 || target >= list.length) return;
    const next = [...list];
    const [item] = next.splice(index, 1);
    next.splice(target, 0, item);
    setList(next.map((entry, order) => ({ ...entry, order: order + 1 })));
  };

  const controls = (index: number, list: Category[] | StatItem[] | NavItem[], remove: () => void, reorder: (direction: -1 | 1) => void) => (
    <div className="flex items-center gap-1"><button type="button" onClick={() => reorder(-1)} disabled={index === 0} className="rounded-lg bg-white/5 p-2 text-zinc-300 disabled:opacity-30" aria-label="Move up"><ArrowUp className="h-3.5 w-3.5" /></button><button type="button" onClick={() => reorder(1)} disabled={index === list.length - 1} className="rounded-lg bg-white/5 p-2 text-zinc-300 disabled:opacity-30" aria-label="Move down"><ArrowDown className="h-3.5 w-3.5" /></button><button type="button" onClick={remove} className="rounded-lg bg-rose-500/10 p-2 text-rose-400" aria-label="Delete"><Trash2 className="h-3.5 w-3.5" /></button></div>
  );

  return <div className="space-y-6 animate-in fade-in duration-200">
    <div className="flex items-center justify-between border-b border-white/10 pb-4"><div><h2 className="font-syne text-xl font-bold text-white">Site Content CMS</h2><p className="text-xs text-zinc-400">Canonical categories, stats, navigation, SEO, and contact settings.</p></div><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-2.5 text-xs font-bold uppercase tracking-wider text-black disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Saving...' : 'Save Site Content'}</button></div>
    <div className="flex flex-wrap gap-2">{(['categories', 'stats', 'navigation', 'seo', 'contact'] as SiteMode[]).map((item) => <button key={item} type="button" onClick={() => setMode(item)} className={`rounded-xl px-3.5 py-2 text-[10px] font-bold uppercase tracking-[0.16em] ${mode === item ? 'bg-emerald-500 text-black' : 'border border-white/10 bg-white/5 text-zinc-300'}`}>{item}</button>)}</div>

    {mode === 'categories' && <div className="space-y-3"><button type="button" onClick={() => setCategories([...categories, { id: `category-${Date.now()}`, name: local('New Category', 'تصنيف جديد'), order: categories.length + 1, visible: true }])} className="inline-flex items-center gap-1 rounded-xl bg-white/10 px-3 py-2 text-xs text-white"><Plus className="h-3.5 w-3.5" />Category</button>{categories.map((item, index) => <div key={item.id} className="grid grid-cols-[1fr_1fr_auto_auto] items-center gap-3 rounded-2xl border border-white/10 bg-[#12141c] p-3"><input value={item.name.en} onChange={(e) => setCategories(categories.map((entry) => entry.id === item.id ? { ...entry, name: { ...entry.name, en: e.target.value } } : entry))} className={inputClass} /><input dir="rtl" value={item.name.ar} onChange={(e) => setCategories(categories.map((entry) => entry.id === item.id ? { ...entry, name: { ...entry.name, ar: e.target.value } } : entry))} className={inputClass} />{controls(index, categories, () => setCategories(categories.filter((entry) => entry.id !== item.id)), (direction) => move(categories, setCategories, index, direction))}<input type="checkbox" checked={item.visible} onChange={(e) => setCategories(categories.map((entry) => entry.id === item.id ? { ...entry, visible: e.target.checked } : entry))} className="accent-emerald-500" /></div>)}</div>}

    {mode === 'stats' && <div className="space-y-3"><button type="button" onClick={() => setStats([...stats, { id: `stat-${Date.now()}`, number: 0, label: local('New Stat', 'إحصائية جديدة'), icon: 'Star', order: stats.length + 1, visible: true }])} className="inline-flex items-center gap-1 rounded-xl bg-white/10 px-3 py-2 text-xs text-white"><Plus className="h-3.5 w-3.5" />Stat</button>{stats.map((item, index) => <div key={item.id} className="grid grid-cols-[80px_1fr_1fr_80px_auto_auto] items-center gap-3 rounded-2xl border border-white/10 bg-[#12141c] p-3"><input type="number" value={item.number} onChange={(e) => setStats(stats.map((entry) => entry.id === item.id ? { ...entry, number: Number(e.target.value) || 0 } : entry))} className={inputClass} /><input value={item.label.en} onChange={(e) => setStats(stats.map((entry) => entry.id === item.id ? { ...entry, label: { ...entry.label, en: e.target.value } } : entry))} className={inputClass} /><input dir="rtl" value={item.label.ar} onChange={(e) => setStats(stats.map((entry) => entry.id === item.id ? { ...entry, label: { ...entry.label, ar: e.target.value } } : entry))} className={inputClass} /><input value={item.suffix || ''} placeholder="Suffix" onChange={(e) => setStats(stats.map((entry) => entry.id === item.id ? { ...entry, suffix: e.target.value } : entry))} className={inputClass} />{controls(index, stats, () => setStats(stats.filter((entry) => entry.id !== item.id)), (direction) => move(stats, setStats, index, direction))}<input type="checkbox" checked={item.visible} onChange={(e) => setStats(stats.map((entry) => entry.id === item.id ? { ...entry, visible: e.target.checked } : entry))} className="accent-emerald-500" /></div>)}</div>}

    {mode === 'navigation' && <div className="space-y-3"><button type="button" onClick={() => setNavItems([...navItems, { id: `nav-${Date.now()}`, label: local('New Link', 'رابط جديد'), target: '#work', isExternal: false, order: navItems.length + 1, visible: true }])} className="inline-flex items-center gap-1 rounded-xl bg-white/10 px-3 py-2 text-xs text-white"><Plus className="h-3.5 w-3.5" />Link</button>{navItems.map((item, index) => <div key={item.id} className="grid grid-cols-[1fr_1fr_1fr_auto_auto] items-center gap-3 rounded-2xl border border-white/10 bg-[#12141c] p-3"><input value={item.label.en} onChange={(e) => setNavItems(navItems.map((entry) => entry.id === item.id ? { ...entry, label: { ...entry.label, en: e.target.value } } : entry))} className={inputClass} /><input dir="rtl" value={item.label.ar} onChange={(e) => setNavItems(navItems.map((entry) => entry.id === item.id ? { ...entry, label: { ...entry.label, ar: e.target.value } } : entry))} className={inputClass} /><input value={item.target} onChange={(e) => setNavItems(navItems.map((entry) => entry.id === item.id ? { ...entry, target: e.target.value } : entry))} className={inputClass} />{controls(index, navItems, () => setNavItems(navItems.filter((entry) => entry.id !== item.id)), (direction) => move(navItems, setNavItems, index, direction))}<input type="checkbox" checked={item.visible} onChange={(e) => setNavItems(navItems.map((entry) => entry.id === item.id ? { ...entry, visible: e.target.checked } : entry))} className="accent-emerald-500" /></div>)}</div>}

    {mode === 'seo' && <div className="grid grid-cols-1 gap-4 rounded-2xl border border-white/10 bg-[#12141c] p-5 md:grid-cols-2">{(['en', 'ar'] as const).map((locale) => <React.Fragment key={locale}><label className="space-y-1 text-xs font-mono text-zinc-400"><span>Site Title {locale.toUpperCase()}</span><input dir={locale === 'ar' ? 'rtl' : 'ltr'} value={seo.siteTitle[locale]} onChange={(e) => setSeo({ ...seo, siteTitle: { ...seo.siteTitle, [locale]: e.target.value } })} className={inputClass} /></label><label className="space-y-1 text-xs font-mono text-zinc-400"><span>Description {locale.toUpperCase()}</span><textarea dir={locale === 'ar' ? 'rtl' : 'ltr'} value={seo.metaDescription[locale]} onChange={(e) => setSeo({ ...seo, metaDescription: { ...seo.metaDescription, [locale]: e.target.value } })} className={inputClass} /></label></React.Fragment>)}<label className="space-y-1 text-xs font-mono text-zinc-400"><span>Canonical URL</span><input value={seo.canonicalUrl} onChange={(e) => setSeo({ ...seo, canonicalUrl: e.target.value })} className={inputClass} /></label><label className="space-y-1 text-xs font-mono text-zinc-400"><span>OG Image</span><input value={seo.ogImage} onChange={(e) => setSeo({ ...seo, ogImage: e.target.value })} className={inputClass} /></label></div>}

    {mode === 'contact' && <div className="space-y-4 rounded-2xl border border-white/10 bg-[#12141c] p-5"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label className="space-y-1 text-xs font-mono text-zinc-400"><span>Email</span><input value={contact.email} onChange={(e) => setContact({ ...contact, email: e.target.value })} className={inputClass} /></label><label className="space-y-1 text-xs font-mono text-zinc-400"><span>WhatsApp</span><input value={contact.whatsapp} onChange={(e) => setContact({ ...contact, whatsapp: e.target.value })} className={inputClass} /></label><label className="space-y-1 text-xs font-mono text-zinc-400"><span>CTA EN</span><input value={contact.ctaText.en} onChange={(e) => setContact({ ...contact, ctaText: { ...contact.ctaText, en: e.target.value } })} className={inputClass} /></label><label className="space-y-1 text-xs font-mono text-zinc-400"><span>CTA AR</span><input dir="rtl" value={contact.ctaText.ar} onChange={(e) => setContact({ ...contact, ctaText: { ...contact.ctaText, ar: e.target.value } })} className={inputClass} /></label></div><div className="grid grid-cols-2 gap-3">{(['showProjectType', 'showBudget', 'showTimeline', 'showProjectBrief'] as const).map((field) => <label key={field} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-zinc-300"><span>{field}</span><input type="checkbox" checked={contact.formFields[field]} onChange={(e) => setContact({ ...contact, formFields: { ...contact.formFields, [field]: e.target.checked } })} className="accent-emerald-500" /></label>)}</div></div>}
  </div>;
};