import React, { useMemo, useState } from 'react';
import { BookOpen, ChevronDown, Info, Search, ShieldCheck } from 'lucide-react';
import { usePortfolio } from '../../../context/PortfolioContext';

type Copy = { en: string; ar: string };
type GuideSection = {
  id: string;
  title: Copy;
  summary: Copy;
  bullets?: Copy[];
  steps?: Copy[];
  example?: Copy;
  note?: Copy;
};

const c = (en: string, ar: string): Copy => ({ en, ar });

const sections: GuideSection[] = [
  { id: 'overview', title: c('Overview', 'نظرة عامة'), summary: c('The dashboard is the editing surface for the portfolio: content, presentation, visibility, inquiries, and account access are separated into focused tabs.', 'لوحة التحكم هي مساحة تحرير الموقع: المحتوى والعرض والظهور والاستفسارات والوصول إلى الحساب موزعة على تبويبات واضحة.'), bullets: [c('Use the left navigation to open Overview, Projects & Reels, Services, Features, Start a Project, Project Inquiry, Availability, Client Logos, Pricing Packages, Tools & Skills, Experience, Education & Certs, Content Creator, Blog & Editorial, Testimonials, Profile & Bio, Social Media, Section Builder, Page Order, Site Content, Messages, Appearance & UI, Media Library, Backup & JSON, Security & Auth, or this guide.', 'استخدم قائمة التنقل لفتح النظرة العامة، المشاريع والريلز، الخدمات، المميزات، ابدأ مشروعًا، استفسارات المشاريع، حالة التوفر، شعارات العملاء، باقات التسعير، الأدوات والمهارات، الخبرة، التعليم والشهادات، محتوى المنصة، المدونة والتحرير، آراء العملاء، الملف الشخصي والسيرة، السوشيال ميديا، بناء الأقسام، ترتيب الصفحات، محتوى الموقع، الرسائل، المظهر والواجهة، مكتبة الوسائط، النسخ الاحتياطي والـ JSON، الأمان والمصادقة، أو هذا الدليل.'), c('The header provides View Live Portfolio, EN/AR language switching, Save All Changes, and Sign Out.', 'يوفر الرأس أزرار عرض الموقع المباشر والتبديل بين EN وAR وحفظ كل التغييرات وتسجيل الخروج.')], note: c('Only controls that exist in the current dashboard are described here.', 'يصف هذا الدليل الأدوات الموجودة حاليًا في لوحة التحكم فقط.') },
  { id: 'getting-started', title: c('Getting started', 'البدء'), summary: c('Open a tab, edit the fields, preview where available, then save the tab or use the global save button.', 'افتح تبويبًا، عدّل الحقول، عاين التغيير عند توفر المعاينة، ثم احفظ التبويب أو استخدم زر الحفظ العام.'), steps: [c('Sign in through Security & Auth, then choose a tab from the navigation.', 'سجّل الدخول عبر الأمان والمصادقة ثم اختر تبويبًا من قائمة التنقل.'), c('Make a focused edit. Forms keep bilingual values where the content model provides EN and AR fields.', 'أجرِ تعديلًا محددًا. تحتفظ النماذج بالقيم الثنائية اللغة عندما يوفر نموذج المحتوى حقول EN وAR.'), c('Select the tab’s Save button, or Save All Changes in the header, and verify the public site with View Live Portfolio.', 'اختر زر الحفظ الخاص بالتبويب أو حفظ كل التغييرات في الرأس، ثم تحقق من الموقع العام عبر عرض الموقع المباشر.')], example: c('Example: update Profile & Bio, save, open the live portfolio, and confirm the hero name, title, bio, and call-to-action.', 'مثال: حدّث الملف الشخصي والسيرة، احفظ، افتح الموقع المباشر، وتحقق من اسم الواجهة والعنوان والسيرة وزر الإجراء.') },
  { id: 'saving', title: c('Saving and publishing', 'الحفظ والنشر'), summary: c('Save All Changes calls PortfolioContext saveData for the current data snapshot. Individual editors may save their own draft.', 'يستدعي حفظ كل التغييرات الدالة saveData في PortfolioContext لحفظ لقطة البيانات الحالية. وقد تحفظ المحررات الفردية مسودتها الخاصة.'), bullets: [c('The header changes to “Syncing…” while the global save is running and then shows a success toast.', 'يتغير زر الرأس إلى «جارٍ المزامنة…» أثناء الحفظ العام ثم تظهر رسالة نجاح.'), c('Page Order, Appearance, media, and content editors also expose a local Save button; use it after completing that editor.', 'توفر محررات ترتيب الصفحات والمظهر والوسائط والمحتوى زر حفظ محليًا أيضًا؛ استخدمه بعد إكمال المحرر.'), c('Public rendering uses the saved portfolio projection; refresh the live view after saving to check the result.', 'يعرض الموقع العام نسخة الموقع المحفوظة؛ حدّث العرض المباشر بعد الحفظ للتحقق من النتيجة.')], note: c('A save is not a publish pipeline or deployment command; it persists dashboard data.', 'الحفظ ليس عملية نشر أو أمر نشر برمجي؛ بل يحفظ بيانات لوحة التحكم.') },
  { id: 'appearance', title: c('Appearance and Theme Studio', 'المظهر واستوديو السمات'), summary: c('Appearance & UI combines named themes, custom design tokens, project presentation, motion, background, and responsive settings.', 'يجمع المظهر والواجهة السمات المسماة ورموز التصميم المخصصة وعرض المشاريع والحركة والخلفية وإعدادات الاستجابة.'), bullets: [c('Choose a named theme from the theme cards. The selected system displays its material and motion description.', 'اختر سمة مسماة من بطاقات السمات. يعرض النظام المحدد وصف الخامة والحركة.'), c('Theme Studio’s Custom theme override enables validated custom tokens while the named theme remains the fallback.', 'يتيح تجاوز السمة المخصصة في استوديو السمات رموزًا مخصصة تم التحقق منها مع بقاء السمة المسماة كخيار احتياطي.'), c('Appearance also controls background intensity, project display mode, card size, project gap, counts, columns, carousel controls/autoplay/loop, cursor, grain, motion, 3D, hero style, and navigation mode.', 'يتحكم المظهر أيضًا في شدة الخلفية ونمط عرض المشاريع وحجم البطاقة والفجوة والأعداد والأعمدة وأدوات/تشغيل/تكرار الكاروسيل والمؤشر والحبيبات والحركة وثلاثي الأبعاد ونمط الواجهة والتنقل.')], note: c('Contrast warnings are informational checks shown by Theme Studio before saving.', 'تحذيرات التباين فحوصات إرشادية يعرضها استوديو السمات قبل الحفظ.') },
  { id: 'colors', title: c('Custom colors, backgrounds, and surfaces', 'الألوان والخلفيات والأسطح المخصصة'), summary: c('Enable custom tokens, then edit the color inputs and range controls exposed by Theme Studio.', 'فعّل الرموز المخصصة ثم عدّل حقول الألوان وعناصر النطاق التي يعرضها استوديو السمات.'), bullets: [c('Color controls include page background, primary/elevated surface, primary/muted text, border, accents, status colors, hero/section/card backgrounds, heading, and body.', 'تشمل الألوان خلفية الصفحة والسطح الأساسي والسطح المرتفع والنص الأساسي والخافت والحدود واللونين البارزين وألوان الحالة وخلفية الواجهة والقسم والبطاقة ولون العناوين والنص.'), c('Range controls include radius, surface opacity, shadow intensity, border intensity, and blur intensity.', 'تشمل عناصر النطاق نصف القطر وشفافية السطح وشدة الظل والحدود والتمويه.'), c('Use the color picker values as valid hex colors. Warnings identify contrast combinations that may need adjustment.', 'استخدم قيم منتقي الألوان بصيغة hex صحيحة. تحدد التحذيرات تراكيب التباين التي قد تحتاج إلى تعديل.')], example: c('Example: enable custom tokens, adjust Accent and Card background, inspect the live preview, then Save.', 'مثال: فعّل الرموز المخصصة، عدّل اللون البارز وخلفية البطاقة، افحص المعاينة المباشرة، ثم احفظ.') },
  { id: 'navigation', title: c('Navigation, page order, and client mode', 'التنقل وترتيب الصفحات ووضع العميل'), summary: c('Navigation mode and public section order are separate settings, while Client Mode changes the presentation selection.', 'نمط التنقل وترتيب أقسام الموقع إعدادان منفصلان، بينما يغير وضع العميل اختيار العرض.'), bullets: [c('Appearance’s Navigation Mode selects the implemented navigation presentation; Page Order lists public sections independently from navigation order.', 'يحدد نمط التنقل في المظهر طريقة التنقل المطبقة؛ ويعرض ترتيب الصفحات الأقسام العامة مستقلًا عن ترتيب التنقل.'), c('In Page Order, use Move up, Move down, and Show/Hide. Feature flags and visibility are both respected, then Save Page Order.', 'في ترتيب الصفحات استخدم التحريك لأعلى ولأسفل والإظهار/الإخفاء. تُحترم أعلام المميزات والظهور معًا، ثم احفظ ترتيب الصفحات.'), c('Appearance exposes Client Mode with Enabled and Standard/Client presentation choices.', 'يعرض المظهر وضع العميل بخياري التفعيل والعرض القياسي/العميل.')], note: c('The sidebar can collapse on desktop and opens as a drawer on mobile; Escape closes the mobile drawer.', 'يمكن طي القائمة الجانبية على سطح المكتب وتفتح كدرج على الهاتف؛ يغلق Escape درج الهاتف.') },
  { id: 'availability', title: c('Availability', 'حالة التوفر'), summary: c('Availability is the canonical place to maintain the public work-status state used by the portfolio.', 'حالة التوفر هي المكان المعتمد لإدارة حالة العمل العامة التي يستخدمها الموقع.'), bullets: [c('Choose the implemented state (available, limited, or booked) and save it in the Availability tab.', 'اختر الحالة المطبقة (متاح أو محدود أو محجوز) واحفظها في تبويب حالة التوفر.'), c('Review the live hero and contact surfaces after saving because the status is shared with those areas.', 'راجع الواجهة ومناطق التواصل المباشرة بعد الحفظ لأن الحالة مشتركة معهما.') ] },
  { id: 'hero-profile', title: c('Hero and Profile', 'الواجهة الرئيسية والملف الشخصي'), summary: c('Profile & Bio supplies identity and hero-facing copy; Site Content holds additional site-level copy and links.', 'يوفر الملف الشخصي والسيرة الهوية والنص الظاهر في الواجهة؛ ويحتوي محتوى الموقع على نصوص وروابط الموقع الإضافية.'), bullets: [c('Edit the profile name, title, bio, CTA-related fields, profile image, and CV/link fields exposed by Profile & Bio.', 'عدّل الاسم والعنوان والسيرة وحقول زر الإجراء وصورة الملف وحقول السيرة الذاتية/الروابط التي يعرضها الملف الشخصي والسيرة.'), c('Use Site Content for the implemented hero/site content fields rather than duplicating text in another tab.', 'استخدم حقول الواجهة/محتوى الموقع المطبقة في محتوى الموقع بدل تكرار النص في تبويب آخر.')], example: c('Keep EN and AR copy aligned so switching the header language produces a complete hero, not a mixed-language fallback.', 'حافظ على اتساق نصي EN وAR حتى ينتج تبديل لغة الرأس واجهة مكتملة لا مزيجًا من اللغتين.') },
  { id: 'projects', title: c('Projects, video, and case studies', 'المشاريع والفيديو ودراسات الحالة'), summary: c('Projects & Reels is the editor for portfolio entries, while Content Creator manages creator video/article items.', 'المشاريع والريلز هو محرر عناصر المحفظة، بينما يدير محتوى المنصة عناصر فيديو/مقال المنشئ.'), bullets: [c('Create or edit project title, description, category, thumbnail/media, featured state, and the project links exposed in the form.', 'أنشئ أو عدّل عنوان المشروع ووصفه وفئته والصورة/الوسائط وحالة التمييز وروابط المشروع التي يعرضها النموذج.'), c('Use Media Library for reusable media and Video fields for the supported provider/URL controls; test an HTTPS URL in the live view.', 'استخدم مكتبة الوسائط للوسائط القابلة لإعادة الاستخدام وحقول الفيديو لعناصر الموفر/الرابط المدعومة؛ اختبر رابط HTTPS في العرض المباشر.'), c('Case-study fields are legacy project fields in the project editor; fill only the fields shown there and save the project.', 'حقول دراسة الحالة هي حقول مشاريع قديمة داخل محرر المشاريع؛ املأ الحقول الظاهرة فقط واحفظ المشروع.')], note: c('The dashboard does not invent a separate case-study publishing workflow; case-study data follows the project editor.', 'لا تنشئ اللوحة مسار نشر منفصلًا لدراسة الحالة؛ تتبع بياناتها محرر المشاريع.') },
  { id: 'media', title: c('Media Library', 'مكتبة الوسائط'), summary: c('Use Media Library to review and manage the media records used by content editors.', 'استخدم مكتبة الوسائط لمراجعة وإدارة سجلات الوسائط التي تستخدمها محررات المحتوى.'), bullets: [c('Prefer stable HTTPS asset URLs and the provider fields offered by the library/editor.', 'فضّل روابط أصول HTTPS المستقرة وحقول الموفر التي توفرها المكتبة/المحررة.'), c('After replacing an asset, save the relevant editor and refresh the live view to verify loading and cropping.', 'بعد استبدال أصل، احفظ المحررة ذات الصلة وحدّث العرض المباشر للتحقق من التحميل والقص.') ] },
  { id: 'services', title: c('Services', 'الخدمات'), summary: c('Services stores the service cards and descriptions presented by the portfolio.', 'تخزن الخدمات بطاقات الخدمات وأوصافها التي يعرضها الموقع.'), bullets: [c('Add or edit a service, keep its bilingual title/description complete, and use the editor’s Save control.', 'أضف خدمة أو عدّلها، وأكمل عنوانها ووصفها باللغتين، ثم استخدم زر الحفظ في المحرر.'), c('Use Tools & Skills for software/tools and disciplines rather than adding them to a service description.', 'استخدم الأدوات والمهارات للبرامج/الأدوات والتخصصات بدل إضافتها إلى وصف الخدمة.') ] },
  { id: 'career', title: c('Experience, education, and certifications', 'الخبرة والتعليم والشهادات'), summary: c('These editors maintain career history and accreditation records displayed by the portfolio.', 'تحافظ هذه المحررات على سجل الخبرة وبيانات الاعتماد التي يعرضها الموقع.'), bullets: [c('Experience & Career History edits positions, organizations, dates, and descriptions shown by the form.', 'تعدل الخبرة والسجل المهني المناصب والمؤسسات والتواريخ والأوصاف التي يعرضها النموذج.'), c('Education & Certs contains separate education and certification/accreditation records; use each editor’s Save and Cancel controls.', 'يحتوي التعليم والشهادات على سجلات منفصلة للتعليم والشهادات/الاعتمادات؛ استخدم زري الحفظ والإلغاء في كل محرر.'), c('Tools & Skills has separate software-tool and core-discipline editors with Save Tool and Save Skill.', 'تحتوي الأدوات والمهارات على محررين منفصلين لأداة البرنامج والتخصص الأساسي مع حفظ الأداة وحفظ المهارة.') ] },
  { id: 'content-blog', title: c('Content Creator and Blog', 'محتوى المنصة والمدونة'), summary: c('Use the dedicated editors for creator items and editorial posts.', 'استخدم المحررات المخصصة لعناصر المنصة والمنشورات التحريرية.'), bullets: [c('Content Creator Hub edits a content piece and its Target Video/Article URL, then Save.', 'يعدل مركز محتوى المنصة قطعة المحتوى ورابط الفيديو/المقال المستهدف، ثم يحفظها.'), c('Blog & Editorial manages blog posts and their bilingual editorial fields; use the form’s save action.', 'تدير المدونة والتحرير المنشورات وحقولها التحريرية الثنائية اللغة؛ استخدم إجراء الحفظ في النموذج.') ] },
  { id: 'logos-pricing-testimonials', title: c('Client logos, pricing, and testimonials', 'شعارات العملاء والتسعير وآراء العملاء'), summary: c('These tabs control trust and offer presentation without changing project records.', 'تتحكم هذه التبويبات في عرض الثقة والعروض دون تغيير سجلات المشاريع.'), bullets: [c('Client Logos supports logo records, website URLs, ordering, preview, removal, and Save.', 'تدعم شعارات العملاء سجلات الشعارات وروابط المواقع والترتيب والمعاينة والحذف والحفظ.'), c('Pricing Packages edits data-driven packages and their presentation variants; save after changing package content.', 'تعدل باقات التسعير الباقات المعتمدة على البيانات ومتغيرات عرضها؛ احفظ بعد تغيير محتوى الباقة.'), c('Testimonials edits client quotes/attribution shown by the implemented testimonials section.', 'تعدل آراء العملاء اقتباسات العملاء ونسبتها التي يعرضها قسم الآراء المطبق.') ] },
  { id: 'contact-inquiries', title: c('Contact and inquiries', 'التواصل والاستفسارات'), summary: c('Public contact settings and received inquiries are intentionally separate.', 'إعدادات التواصل العامة والاستفسارات الواردة منفصلتان عمدًا.'), bullets: [c('Start a Project configures the public project-intake form and its contact fields.', 'يهيئ ابدأ مشروعًا نموذج استقبال المشاريع العام وحقول التواصل.'), c('Project Inquiry controls the optional Project brief URL field, its English/Arabic labels, and the feature toggle.', 'تتحكم استفسارات المشاريع في حقل رابط موجز المشروع الاختياري وتسميتيه العربية والإنجليزية ومفتاح الميزة.'), c('Messages and Project Inquiry are the authenticated admin views for incoming records; review, update, and save only the controls they expose.', 'الرسائل واستفسارات المشاريع هما عرضا الإدارة الموثقان للسجلات الواردة؛ راجع وعدّل واحفظ الأدوات التي يعرضانها فقط.') ] },
  { id: 'features', title: c('Feature flags', 'أعلام المميزات'), summary: c('Features toggles implemented capabilities that are also respected by section visibility and navigation.', 'تبدّل المميزات القدرات المطبقة التي تراعيها أيضًا رؤية الأقسام والتنقل.'), bullets: [c('Change a flag in Features, save, then verify the dependent section in the live portfolio.', 'غيّر علمًا في المميزات واحفظ، ثم تحقق من القسم التابع في الموقع المباشر.'), c('A disabled feature can remain in Page Order but will not be treated as enabled; visibility and the flag both matter.', 'قد تبقى الميزة المعطلة في ترتيب الصفحات لكنها لا تعامل كمفعلة؛ الظهور والعلم مهمان معًا.') ] },
  { id: 'responsive', title: c('Responsive administration', 'الإدارة المتجاوبة'), summary: c('The dashboard adapts its navigation and project presentation for desktop, tablet, and mobile.', 'تتكيف لوحة التحكم في التنقل وعرض المشاريع مع سطح المكتب والجهاز اللوحي والهاتف.'), bullets: [c('On desktop, collapse the sidebar with its arrow button; hover labels remain available when collapsed.', 'على سطح المكتب اطوِ القائمة بزر السهم؛ وتبقى التسميات متاحة عند المرور أثناء الطي.'), c('On mobile, open the menu button, choose a tab, or press Escape/close the backdrop to dismiss it.', 'على الهاتف افتح زر القائمة واختر تبويبًا، أو اضغط Escape/الإغلاق على الخلفية لإخفائها.'), c('Appearance’s Desktop, Tablet, and Mobile column controls affect project presentation; choose values that fit the selected display mode.', 'تؤثر أعمدة سطح المكتب والجهاز اللوحي والهاتف في المظهر على عرض المشاريع؛ اختر قيمًا تناسب نمط العرض المحدد.') ] },
  { id: 'preview-reset', title: c('Theme preview, save, cancel, and reset', 'معاينة السمة والحفظ والإلغاء وإعادة الضبط'), summary: c('Theme Studio previews token edits immediately and keeps them local until you save.', 'يعاين استوديو السمات تعديلات الرموز فورًا ويبقيها محلية حتى تحفظها.'), steps: [c('Edit a token or select a named theme. The Live preview is active while editing.', 'عدّل رمزًا أو اختر سمة مسماة. تكون المعاينة المباشرة مفعلة أثناء التحرير.'), c('Use Cancel to restore the last saved tokens, enabled state, and theme name.', 'استخدم إلغاء لاستعادة الرموز وحالة التفعيل واسم السمة المحفوظة آخر مرة.'), c('Use Reset theme to derive the custom draft from the selected named theme, then Save if the result is correct.', 'استخدم إعادة ضبط السمة لاشتقاق المسودة المخصصة من السمة المسماة المحددة، ثم احفظ إن كانت النتيجة صحيحة.'), c('Use Save in Theme Studio for theme tokens, and Save Appearance for the surrounding appearance settings.', 'استخدم حفظ في استوديو السمات لرموز السمة، وحفظ المظهر لإعدادات المظهر الأخرى.') ] },
  { id: 'troubleshooting', title: c('Troubleshooting', 'استكشاف الأخطاء'), summary: c('Use these checks before changing data again.', 'استخدم هذه الفحوصات قبل تعديل البيانات مرة أخرى.'), bullets: [c('Stale view: save, choose View Live Portfolio, and hard-refresh the browser.', 'عرض قديم: احفظ واختر عرض الموقع المباشر ثم أعد تحميل المتصفح تحميلًا كاملًا.'), c('Media/video not loading: check that the URL is HTTPS, the provider is supported by the field, and the asset is reachable.', 'الوسائط/الفيديو لا يعملان: تحقق من أن الرابط HTTPS وأن الموفر مدعوم في الحقل وأن الأصل قابل للوصول.'), c('Appearance looks unchanged: confirm the custom-token checkbox is enabled, save Theme Studio, then save Appearance if you changed its other settings.', 'المظهر لم يتغير: تأكد من تفعيل مربع الرموز المخصصة، واحفظ استوديو السمات، ثم احفظ المظهر إذا غيّرت إعداداته الأخرى.'), c('Save error or missing inquiry: verify the admin session, network, and the tab’s own save feedback before retrying.', 'خطأ في الحفظ أو استفسار مفقود: تحقق من جلسة الإدارة والشبكة ورسالة الحفظ الخاصة بالتبويب قبل إعادة المحاولة.') ] },
];

export const AdminGuideTab: React.FC = () => {
  const { language } = usePortfolio();
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState('overview');
  const isAr = language === 'ar';
  const text = (value: Copy) => value[language];
  const filtered = useMemo(() => sections.filter((section) => `${section.title.en} ${section.title.ar} ${section.summary.en} ${section.summary.ar}`.toLowerCase().includes(query.toLowerCase())), [query]);

  return (
    <div className="space-y-6">
      <header className="border-b border-[var(--border)] pb-5">
        <div className="flex items-center gap-2 text-xs font-mono uppercase tracking-[0.2em] text-[var(--color-accent)]"><BookOpen className="h-4 w-4" /> {isAr ? 'دليل لوحة التحكم' : 'Dashboard Guide'}</div>
        <h2 className="mt-2 text-2xl font-bold font-syne">{isAr ? 'دليل التشغيل الإداري' : 'Admin operating manual'}</h2>
        <p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">{isAr ? 'مرجع ثنائي اللغة لإدارة الميزات المطبقة وحفظها ومعاينتها بأمان.' : 'A bilingual reference for operating, previewing, and saving the implemented dashboard features safely.'}</p>
      </header>

      <div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]">
        <aside className="hidden self-start lg:sticky lg:top-4 lg:block" aria-label={isAr ? 'تنقل الدليل' : 'Guide navigation'}>
          <p className="mb-2 px-2 text-[10px] font-mono uppercase tracking-[0.18em] text-[var(--muted)]">{isAr ? 'الأقسام' : 'Sections'}</p>
          <nav className="space-y-1">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className="block rounded-lg px-2 py-1.5 text-xs text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]">{text(section.title)}</a>)}</nav>
        </aside>
        <div className="min-w-0 space-y-4">
          <details className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 lg:hidden">
            <summary className="cursor-pointer text-sm font-semibold">{isAr ? 'فتح فهرس الدليل' : 'Open guide navigation'}</summary>
            <nav className="mt-3 grid gap-1 sm:grid-cols-2">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className="rounded-lg px-2 py-1.5 text-xs text-[var(--muted)] hover:bg-[var(--surface-muted)]">{text(section.title)}</a>)}</nav>
          </details>
          <label className="relative block">
            <Search className="pointer-events-none absolute start-3 top-3 h-4 w-4 text-[var(--muted)]" />
            <input aria-label={isAr ? 'البحث في دليل لوحة التحكم' : 'Search dashboard guide'} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={isAr ? 'ابحث في الدليل' : 'Search the guide'} className="w-full rounded-xl border border-[var(--border)] bg-[var(--input-bg)] py-2.5 ps-10 pe-3 text-sm text-[var(--foreground)] outline-none focus:border-[var(--color-accent)]" />
          </label>
          {filtered.map((section) => <section id={section.id} key={section.id} className="scroll-mt-4 overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
            <button type="button" aria-expanded={open === section.id} onClick={() => setOpen(open === section.id ? '' : section.id)} className="flex w-full items-center justify-between gap-4 p-4 text-start">
              <span><span className="block font-semibold text-[var(--foreground)]">{text(section.title)}</span><span className="mt-1 block text-xs font-normal leading-5 text-[var(--muted)]">{text(section.summary)}</span></span>
              <ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${open === section.id ? 'rotate-180' : ''}`} />
            </button>
            {open === section.id && <div className="border-t border-[var(--border-subtle)] p-4 text-sm leading-7 text-[var(--muted)]">
              {section.bullets && <ul className="space-y-2">{section.bullets.map((bullet) => <li key={bullet.en} className="flex gap-2"><ShieldCheck className="mt-1 h-4 w-4 shrink-0 text-[var(--color-accent)]" /><span>{text(bullet)}</span></li>)}</ul>}
              {section.steps && <ol className="mt-1 space-y-2">{section.steps.map((step, index) => <li key={step.en} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[var(--accent-muted)] text-xs font-bold text-[var(--color-accent)]">{index + 1}</span><span>{text(step)}</span></li>)}</ol>}
              {section.example && <div className="mt-4 rounded-xl border border-[var(--color-accent)]/30 bg-[var(--accent-muted)] p-3 text-xs"><strong className="me-1 text-[var(--color-accent)]">{isAr ? 'مثال:' : 'Example:'}</strong>{text(section.example)}</div>}
              {section.note && <div className="mt-4 flex gap-2 rounded-xl border border-sky-400/30 bg-sky-400/10 p-3 text-xs"><Info className="mt-1 h-4 w-4 shrink-0 text-sky-300" /><span>{text(section.note)}</span></div>}
            </div>}
          </section>)}
          {filtered.length === 0 && <p className="rounded-xl border border-[var(--border)] p-5 text-sm text-[var(--muted)]">{isAr ? 'لا توجد أقسام مطابقة.' : 'No matching sections.'}</p>}
        </div>
      </div>
    </div>
  );
};
